name: example
description: A new Get Server application.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  faker: ^1.3.0
  mysql_simple_orm:
    path: ../

dev_dependencies:
  test: 1.15.3
  pedantic: 1.9.2
