name: mysql_simple_orm
description: initial sketch of a mysql dart orm
version: 0.1.0-beta
homepage: https://github.com/CpdnCristiano/orm_mysql

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  mysql1: ^0.17.1

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
